---
# TODO: Download binaries to temp folder and clean up afterwards.
- name: download hound binaries
  command: "{{ go_root }}/bin/go get github.com/etsy/hound/cmds/..."
  environment:
    GOROOT: "{{ go_root }}"
    GOPATH: /tmp

- name: Copy binaries to /usr/local/bin
  copy: remote_src=True src="/tmp/bin/{{ item }}" dest="/usr/local/bin/{{item}}" mode=755
  become: yes
  with_items:
    - hound
    - houndd

- name: create hound data dir in /etc/hound
  become: yes
  file:
    dest: /etc/hound
    state: directory
    owner: "{{ hound_user }}"
    group: "{{ hound_user }}"

- name: Write hound config.
  copy:
    content: "{{ hound_config | to_nice_json(indent=2) }}"
    dest: /etc/hound/config.json
  notify:
    - start hound

- name: Write systemd service file
  template:
    src: hound.service.j2
    dest: /etc/systemd/system/hound.service
    owner: root
    group: root
    mode: 0640
  become: yes
  notify:
    - start hound

- name: Write nginx config to /etc/nginx/sites-available/hound.conf
  template:
    src: hound.conf.j2
    dest: /etc/nginx/sites-available/hound.conf
    owner: root
    group: root
    mode: 0640
  become: yes
  notify:
    - reload nginx

- name: enable the nginx config
  file:
    src: /etc/nginx/sites-available/hound.conf
    dest: /etc/nginx/sites-enabled/hound.conf
    state: link
  become: yes
  notify:
    - reload nginx
